-- CREAR BASE DE DATOS
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'STEAM')
    CREATE DATABASE STEAM;
GO

USE STEAM
GO


-- TABLA STATUS
CREATE TABLE Status(
    StatusID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	Code NVARCHAR(20) NOT NULL,
    ShowName NVARCHAR(20) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO


--TABLA Usuario
CREATE TABLE Users (
    UserID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) UNIQUE,
    Password NVARCHAR(255),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    DeletedAt DATETIME2,
    StatusID INT,
    FOREIGN KEY (StatusID) REFERENCES Status(StatusID)
);

-- TABLA AMIGOS
CREATE TABLE Friends (
    UserID UNIQUEIDENTIFIER,
    FriendID UNIQUEIDENTIFIER,
    AddedAt DATETIME2 DEFAULT SYSUTCDATETIME(),

    PRIMARY KEY (UserID, FriendID),

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (FriendID) REFERENCES Users(UserID)
);

--TABLA DESARROLLADOR
CREATE TABLE Developer (
    DeveloperID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    DeveloperName NVARCHAR(150),
    Email NVARCHAR(150),
	Password NVARCHAR(255),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    DeletedAt DATETIME2
);
-- TABLA EDITOR
CREATE TABLE Publishers (
    PublisherID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    PublisherName NVARCHAR(150),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    DeletedAt DATETIME2
);

--TABLA JUEGOS
CREATE TABLE Games (
    GameID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Title NVARCHAR(200),
    Description NVARCHAR(1000),
    ReleaseDate DATE,
    Price DECIMAL(10,2),

    DeveloperID UNIQUEIDENTIFIER,
    PublisherID UNIQUEIDENTIFIER,

    DeletedAt DATETIME2,

    FOREIGN KEY (DeveloperID) REFERENCES Developer(DeveloperID),
    FOREIGN KEY (PublisherID) REFERENCES Publishers(PublisherID)
);

-- TABLA LOGROS:
CREATE TABLE Achievements (
    AchievementID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(200),
    Description NVARCHAR(500),
    GameID UNIQUEIDENTIFIER,

    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- TABLA LOGROS DE USUARIO:
CREATE TABLE UserAchievements (
    UserAchievementID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserID UNIQUEIDENTIFIER,
    AchievementID INT,
    UnlockedAt DATETIME2,

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (AchievementID) REFERENCES Achievements(AchievementID)
);

--TABLA DE RESEÑA
CREATE TABLE Reviews (
    ReviewID INT IDENTITY(1,1) PRIMARY KEY,
    UserID UNIQUEIDENTIFIER,
    GameID UNIQUEIDENTIFIER,
    IsRecommended BIT,
    Comment NVARCHAR(1000),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2,
    DeletedAt DATETIME2,

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- TABLA DE RESPUESTAS DE RESEÑAS
CREATE TABLE ReviewAnswers (
	ReviewAnswersId INT NOT NULL IDENTITY(1,1),
    ReviewId INT,
    UserID UNIQUEIDENTIFIER,
	Comment NVARCHAR(1000),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2,
    DeletedAt DATETIME2,

    PRIMARY KEY (ReviewId, UserID),

    FOREIGN KEY (ReviewId) REFERENCES Reviews(ReviewID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- TABLA DE LIBRERIA
CREATE TABLE Library (
    LibraryID INT IDENTITY(1,1) PRIMARY KEY,
    UserID UNIQUEIDENTIFIER,
    GameID UNIQUEIDENTIFIER,
    PurchasePrice DECIMAL(10,2),
    PurchaseDate DATETIME2,

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- TABLA LISTA DE DESEOS
CREATE TABLE Wishlist (
    WishlistID INT IDENTITY(1,1) PRIMARY KEY,
    UserID UNIQUEIDENTIFIER,
    GameID UNIQUEIDENTIFIER,
    AddedAt DATETIME2 DEFAULT SYSUTCDATETIME(),

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- TABLA DE SESIONES

CREATE TABLE Sessions (
    SessionID INT IDENTITY(1,1) PRIMARY KEY,
    UserID UNIQUEIDENTIFIER,
    GameID UNIQUEIDENTIFIER,
    StartTime DATETIME2,
    EndTime DATETIME2,

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- TABLA DE DLCs
CREATE TABLE DLCs (
    DLCID INT IDENTITY(1,1) PRIMARY KEY,
    DLCName NVARCHAR(200),
    Price DECIMAL(10,2),
    AddedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    GameID UNIQUEIDENTIFIER,

    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);

-- TABLA DE GENEROS
CREATE TABLE Genre (
    GenreID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100)
);

--TABLA DE GENERO DE JUEGOS:
CREATE TABLE Game_Genre (
    GameGenreID INT IDENTITY(1,1) PRIMARY KEY,
    GameID UNIQUEIDENTIFIER,
    GenreID INT,

    FOREIGN KEY (GameID) REFERENCES Games(GameID),
    FOREIGN KEY (GenreID) REFERENCES Genre(GenreID)
);

-- TABLA DE OFERTAS:
CREATE TABLE Offers (
    OfferID INT IDENTITY(1,1) PRIMARY KEY,
    GameID UNIQUEIDENTIFIER,
    Discount INT,
    StartDate DATETIME2,
    EndDate DATETIME2,

    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);
